cmake-ci update autocommit

diff --git a/.ci/.orig/.github/workflows/mambaru.yml b/.ci/.orig/.github/workflows/mambaru.yml
--- a/.ci/.orig/.github/workflows/mambaru.yml
+++ b/.ci/.orig/.github/workflows/mambaru.yml
@@ -11,38 +11,28 @@ jobs:
     steps:
       - uses: actions/checkout@v1
 
-      - name: Установка пакетов
+      - name: Install packages
         run: |
           sudo locale-gen ru_RU
           sudo locale-gen ru_RU.UTF-8
           sudo update-locale
-          
-          sudo apt-get install -y libboost-system-dev libboost-program-options-dev
-          sudo apt-get install -y libboost-filesystem-dev libboost-date-time-dev libboost-regex-dev
           sudo apt-get install -y lcov
-          
-          if [[ "${GITHUB_REPOSITORY}" == *"prefixdb"* ]]; then
-            sudo apt-get install libsnappy-dev
-            sudo apt-get install zlib1g-dev
-            sudo apt-get install libbz2-dev
-            sudo apt-get install liblz4-dev
-            sudo apt-get install libzstd-dev
-          fi
+        working-directory: ./.github/workflows
 
-      - name: Подключение субмодулей (прописаны в cmake)
+      - name: Coverage report and push to master branches
         run: |
-          mkdir -p build
-          pushd build
-            cmake ..
-          popd
-
-      - name: Коммит субмодулей
-        run: |
-          git checkout -b mamba-ready
           echo "Субмодули подключаються при первой сборке (фиксируем их)"
           git config --global user.email "migashko@gmail.com"
           git config --global user.name "Vladimir Migashko"
+          git config pull.rebase true
+          git pull origin master
+          make coverage-report
           git add .
           git commit -am "[subm] build submodule autocommit" || true
-          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git mamba-ready:mamba-ready
-          git push -f https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git mamba-ready:mamba-ready
+          pushd build
+             export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
+             bash <(curl -s https://codecov.io/bash)
+          popd
+          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
+          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git :mamba-ready 2> /dev/null || true
+          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git :mambaru || echo "Delete mambaru FAIL"
